services:
  web:
    image: "php:8.3-fpm-alpine"
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html     
    depends_on:
      - php
    networks:
      - app-network    

  mysql:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: test1
      MYSQL_DATABASE: wp
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8081:80'
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - db

volumes:
  db:

networks:
  app-network:
    driver: bridge