services:
  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx_app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html     
    depends_on:
      - php
    networks:
      - app-network    

  mysql:
    image: "mysql"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - db:/var/lib/mysql
      - ./db_seed:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8081:80'
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  db:

networks:
  app-network:
    driver: bridge